version: '3.6'

services:
  mysql:
    container_name: article-mysql
    platform: linux/amd64
    image: mysql
    restart: always
    ports: 
      - "3306:3306"
    volumes:
      - ./.db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=article
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=development
      - MYSQL_PASSWORD=d3v3l0pm3nt
    networks:
      - article-network

networks:
  article-network:
    driver: bridge