version: '3.6'

services:
  mysql:
    container_name: student-mysql
    platform: linux/amd64
    image: mysql
    restart: always
    ports: 
      - "3306:3306"
    volumes:
      - ./.db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=student
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=development
      - MYSQL_PASSWORD=d3v3l0pm3nt
    networks:
      - student-network

networks:
  student-network:
    driver: bridge